tokenizer:
  model_name: t5-large
  padding_side: right
  truncation_side: right
  pad_token_as_eos_token: False
  model_max_length: 1024

datapool:
  id: openai_summ
  args:
    prompt_prefix: "critique: "
    stage: critique

alg:
  id: supervised
  training_args:
    per_device_train_batch_size: 2
    logging_steps: 5000
    num_train_epochs: 7
    weight_decay: 0.1
    lr_scheduler_type: cosine
    learning_rate: 0.00001
    save_total_limit: 1
  model_type: seq2seq
  model_name: t5-large
  generation_kwargs:
    do_sample: True
    top_k: 0
    temperature: 0.7
    min_length: 20
    max_new_tokens: 150
    post_processing_fn: null

train_evaluation:
  eval_batch_size: 16
  seed: 0
  metrics:
    - id: rouge
    - id: bleu
      args: {}
    - id: bert_score
      args:
        language: en
    - id: diversity
      args: {}